package models

import "gorm.io/gorm"

// Balance for company
type Balance struct {
	gorm.Model
	Category                           string
	CompanyCode                        string
	ReportName                         string
	ReportDate                         uint
	TotalAssets                        float32
	TotalAssetsIncrease                float32
	TotalLiab                          float32
	TotalLiabIncrease                  float32
	AssetLiabRatio                     float32
	AssetLiabRatioIncrease             float32
	TotalQuityAtsopc                   float32
	TotalQuityAtsopcIncrease           float32
	TradableFnnclAssets                float32
	TradableFnnclAssetsIncrease        float32
	InterestReceivable                 float32
	InterestReceivableIncrease         float32
	SaleableFinacialAssets             float32
	SaleableFinacialAssetsIncrease     float32
	HeldToMaturityInvest               float32
	HeldToMaturityInvestIncrease       float32
	FixedAsset                         float32
	FixedAssetIncrease                 float32
	IntangibleAssets                   float32
	IntangibleAssetsIncrease           float32
	ConstructionInProcess              float32
	ConstructionInProcessIncrease      float32
	DtAssets                           float32
	DtAssetsIncrease                   float32
	TradableFnnclLiab                  float32
	TradableFnnclLiabIncrease          float32
	PayrollPayable                     float32
	PayrollPayableIncrease             float32
	TaxPayable                         float32
	TaxPayableIncrease                 float32
	EstimatedLiab                      float32
	EstimatedLiabIncrease              float32
	DtLiab                             float32
	DtLiabIncrease                     float32
	BondPayable                        float32
	BondPayableIncrease                float32
	Shares                             float32
	SharesIncrease                     float32
	CapitalReserve                     float32
	CapitalReserveIncrease             float32
	EarnedSurplus                      float32
	EarnedSurplusIncrease              float32
	UndstrbtdProfit                    float32
	UndstrbtdProfitIncrease            float32
	MinorityEquity                     float32
	MinorityEquityIncrease             float32
	TotalHoldersEquity                 float32
	TotalHoldersEquityIncrease         float32
	TotalLiabAndHoldersEquity          float32
	TotalLiabAndHoldersEquityIncrease  float32
	LtEquityInvest                     float32
	LtEquityInvestIncrease             float32
	DerivativeFnnclLiab                float32
	DerivativeFnnclLiabIncrease        float32
	GeneralRiskProvision               float32
	GeneralRiskProvisionIncrease       float32
	FrgnCurrencyConvertDiff            float32
	FrgnCurrencyConvertDiffIncrease    float32
	Goodwill                           float32
	GoodwillIncrease                   float32
	InvestProperty                     float32
	InvestPropertyIncrease             float32
	InterestPayable                    float32
	InterestPayableIncrease            float32
	TreasuryStock                      float32
	TreasuryStockIncrease              float32
	OthrCompreIncome                   float32
	OthrCompreIncomeIncrease           float32
	OthrEquityInstruments              float32
	OthrEquityInstrumentsIncrease      float32
	CurrencyFunds                      float32
	CurrencyFundsIncrease              float32
	BillsReceivable                    float32
	BillsReceivableIncrease            float32
	AccountReceivable                  float32
	AccountReceivableIncrease          float32
	PrePayment                         float32
	PrePaymentIncrease                 float32
	DividendReceivable                 float32
	DividendReceivableIncrease         float32
	OthrReceivables                    float32
	OthrReceivablesIncrease            float32
	Inventory                          float32
	InventoryIncrease                  float32
	NcaDueWithinOneYear                float32
	NcaDueWithinOneYearIncrease        float32
	OthrCurrentAssets                  float32
	OthrCurrentAssetsIncrease          float32
	CurrentAssetsSi                    float32
	CurrentAssetsSiIncrease            float32
	TotalCurrentAssets                 float32
	TotalCurrentAssetsIncrease         float32
	LtReceivable                       float32
	LtReceivableIncrease               float32
	DevExpenditure                     float32
	DevExpenditureIncrease             float32
	LtDeferredExpense                  float32
	LtDeferredExpenseIncrease          float32
	OthrNoncurrentAssets               float32
	OthrNoncurrentAssetsIncrease       float32
	NoncurrentAssetsSi                 float32
	NoncurrentAssetsSiIncrease         float32
	TotalNoncurrentAssets              float32
	TotalNoncurrentAssetsIncrease      float32
	StLoan                             float32
	StLoanIncrease                     float32
	BillPayable                        float32
	BillPayableIncrease                float32
	AccountsPayable                    float32
	AccountsPayableIncrease            float32
	PreReceivable                      float32
	PreReceivableIncrease              float32
	DividendPayable                    float32
	DividendPayableIncrease            float32
	OthrPayables                       float32
	OthrPayablesIncrease               float32
	NoncurrentLiabDueIn1y              float32
	NoncurrentLiabDueIn1yIncrease      float32
	CurrentLiabSi                      float32
	CurrentLiabSiIncrease              float32
	TotalCurrentLiab                   float32
	TotalCurrentLiabIncrease           float32
	LtLoan                             float32
	LtLoanIncrease                     float32
	LtPayable                          float32
	LtPayableIncrease                  float32
	SpecialPayable                     float32
	SpecialPayableIncrease             float32
	OthrNonCurrentLiab                 float32
	OthrNonCurrentLiabIncrease         float32
	NoncurrentLiabSi                   float32
	NoncurrentLiabSiIncrease           float32
	TotalNoncurrentLiab                float32
	TotalNoncurrentLiabIncrease        float32
	SalableFinancialAssets             float32
	SalableFinancialAssetsIncrease     float32
	OthrCurrentLiab                    float32
	OthrCurrentLiabIncrease            float32
	ArAndBr                            float32
	ArAndBrIncrease                    float32
	ContractualAssets                  float32
	ContractualAssetsIncrease          float32
	BpAndAp                            float32
	BpAndApIncrease                    float32
	ContractLiabilities                float32
	ContractLiabilitiesIncrease        float32
	ToSaleAsset                        float32
	ToSaleAssetIncrease                float32
	OtherEqInsInvest                   float32
	OtherEqInsInvestIncrease           float32
	OtherIlliquidFnnclAssets           float32
	OtherIlliquidFnnclAssetsIncrease   float32
	FixedAssetSum                      float32
	FixedAssetSumIncrease              float32
	FixedAssetsDisposal                float32
	FixedAssetsDisposalIncrease        float32
	ConstructionInProcessSum           float32
	ConstructionInProcessSumIncrease   float32
	ProjectGoodsAndMaterial            float32
	ProjectGoodsAndMaterialIncrease    float32
	ProductiveBiologicalAssets         float32
	ProductiveBiologicalAssetsIncrease float32
	OilAndGasAsset                     float32
	OilAndGasAssetIncrease             float32
	ToSaleDebt                         float32
	ToSaleDebtIncrease                 float32
	LtPayableSum                       float32
	LtPayableSumIncrease               float32
	NoncurrentLiabDi                   float32
	NoncurrentLiabDiIncrease           float32
	PerpetualBond                      float32
	PerpetualBondIncrease              float32
	SpecialReserve                     float32
	SpecialReserveIncrease             float32
}
